# Assignment lab 08
- 10.05.21

## Master Class: Machine Learning (5MI2018)
- Faculty of Economic Science
- University of Neuchatel (Switzerland)
- Lab 8, see ML21_Exercise_8.pdf for more information

## Authors: 
- Romain Claret @RomainClaret
- Sylvain Robert-Nicoud @Nic0uds

| Variable   name                                    | Variable definition                                                                                                                                                                                                              |
|----------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Identifier variables                               |                                                                                                                                                                                                                                  |
| countrycode                                        | 3-letter ISO country code                                                                                                                                                                                                        |
| country                                            | Country name                                                                                                                                                                                                                     |
| currency_unit                                      | Currency unit                                                                                                                                                                                                                    |
| year                                               | Year                                                                                                                                                                                                                             |
|                                                    |                                                                                                                                                                                                                                  |
| Real   GDP, employment and population levels       |                                                                                                                                                                                                                                  |
| rgdpe                                              | Expenditure-side real GDP at   chained PPPs (in mil. 2017US$)                                                                                                                                                                    |
| rgdpo                                              | Output-side real GDP at chained   PPPs (in mil. 2017US$)                                                                                                                                                                         |
| pop                                                | Population (in millions)                                                                                                                                                                                                         |
| emp                                                | Number of persons engaged (in   millions)                                                                                                                                                                                        |
| avh                                                | Average annual hours worked by   persons engaged                                                                                                                                                                                 |
| hc                                                 | Human capital index, based on   years of schooling and returns to education; see Human capital in PWT9.                                                                                                                          |
|                                                    |                                                                                                                                                                                                                                  |
| Current   price GDP, capital and TFP               |                                                                                                                                                                                                                                  |
| ccon                                               | Real consumption of households   and government, at current PPPs (in mil. 2017US$)                                                                                                                                               |
| cda                                                | Real domestic absorption, (real   consumption plus investment), at current PPPs (in mil. 2017US$)                                                                                                                                |
| cgdpe                                              | Expenditure-side real GDP at   current PPPs (in mil. 2017US$)                                                                                                                                                                    |
| cgdpo                                              | Output-side real GDP at current   PPPs (in mil. 2017US$)                                                                                                                                                                         |
| cn                                                 | Capital stock at current PPPs   (in mil. 2017US$)                                                                                                                                                                                |
| ck                                                 | Capital services levels at   current PPPs (USA=1)                                                                                                                                                                                |
| ctfp                                               | TFP level at current PPPs (USA=1)                                                                                                                                                                                                |
| cwtfp                                              | Welfare-relevant TFP levels at   current PPPs (USA=1)                                                                                                                                                                            |
|                                                    |                                                                                                                                                                                                                                  |
| National   accounts-based variables                |                                                                                                                                                                                                                                  |
| rgdpna                                             | Real GDP at constant 2017   national prices (in mil. 2017US$)                                                                                                                                                                    |
| rconna                                             | Real consumption at constant   2017 national prices (in mil. 2017US$)                                                                                                                                                            |
| rdana                                              | Real domestic absorption at   constant 2017 national prices (in mil. 2017US$)                                                                                                                                                    |
| rnna                                               | Capital stock at constant 2017   national prices (in mil. 2017US$)                                                                                                                                                               |
| rkna                                               | Capital services at constant   2017 national prices (2017=1)                                                                                                                                                                     |
| rtfpna                                             | TFP at constant national prices   (2017=1)                                                                                                                                                                                       |
| rwtfpna                                            | Welfare-relevant TFP at constant   national prices (2017=1)                                                                                                                                                                      |
| labsh                                              | Share of labour compensation in   GDP at current national prices                                                                                                                                                                 |
| irr                                                | Real internal rate of return                                                                                                                                                                                                     |
| delta                                              | Average depreciation rate of the   capital stock                                                                                                                                                                                 |
|                                                    |                                                                                                                                                                                                                                  |
| Exchange   rates and GDP price levels              |                                                                                                                                                                                                                                  |
| xr                                                 | Exchange rate, national   currency/USD (market+estimated)                                                                                                                                                                        |
| pl_con                                             | Price level of CCON (PPP/XR),   price level of USA GDPo in 2017=1                                                                                                                                                                |
| pl_da                                              | Price level of CDA (PPP/XR),   price level of USA GDPo in 2017=1                                                                                                                                                                 |
| pl_gdpo                                            | Price level of CGDPo (PPP/XR),   price level of USA GDPo in 2017=1                                                                                                                                                               |
|                                                    |                                                                                                                                                                                                                                  |
| Data information variables                         |                                                                                                                                                                                                                                  |
| i_cig                                              | 0/1/2/3/4: relative price data   for consumption, investment and government is extrapolated (0), benchmark   (1), interpolated (2), ICP PPP timeseries: benchmark or interpolated (3)   or  ICP PPP timeseries: extrapolated (4) |
| i_xm                                               | 0/1/2: relative price data for   exports and imports is extrapolated (0), benchmark (1) or interpolated (2)                                                                                                                      |
| i_xr                                               | 0/1: the exchange rate is   market-based (0) or estimated (1)                                                                                                                                                                    |
| i_outlier                                          | 0/1: the observation on pl_gdpe   or pl_gdpo is not an outlier (0) or an outlier (1)                                                                                                                                             |
| i_irr                                              | 0/1/2/3: the observation for irr   is not an outlier (0), may be biased due to a low capital share (1), hit the   lower bound of 1 percent (2), or is an outlier (3)                                                             |
| cor_exp                                            | Correlation between expenditure   shares of the country and the US (benchmark observations only)                                                                                                                                 |
| statcap                                            | Statistical capacity indicator   (source: World Bank, developing countries only)                                                                                                                                                 |
|                                                    |                                                                                                                                                                                                                                  |
| Shares in CGDPo                                    |                                                                                                                                                                                                                                  |
| csh_c                                              | Share of household consumption   at current PPPs                                                                                                                                                                                 |
| csh_i                                              | Share of gross capital formation   at current PPPs                                                                                                                                                                               |
| csh_g                                              | Share of government consumption   at current PPPs                                                                                                                                                                                |
| csh_x                                              | Share of merchandise exports at   current PPPs                                                                                                                                                                                   |
| csh_m                                              | Share of merchandise imports at   current PPPs                                                                                                                                                                                   |
| csh_r                                              | Share of residual trade and GDP   statistical discrepancy at current PPPs                                                                                                                                                        |
|                                                    |                                                                                                                                                                                                                                  |
| Price   levels, expenditure categories and capital |                                                                                                                                                                                                                                  |
| pl_c                                               | Price level of household   consumption,  price level of USA GDPo   in 2017=1                                                                                                                                                     |
| pl_i                                               | Price level of capital   formation,  price level of USA GDPo in   2017=1                                                                                                                                                         |
| pl_g                                               | Price level of government   consumption,  price level of USA GDPo   in 2017=1                                                                                                                                                    |
| pl_x                                               | Price level of exports, price   level of USA GDPo in 2017=1                                                                                                                                                                      |
| pl_m                                               | Price level of imports, price   level of USA GDPo in 2017=1                                                                                                                                                                      |
| pl_n                                               | Price level of the capital   stock, price level of USA in 2017=1                                                                                                                                                                 |
| pl_k                                               | Price level of the capital   services, price level of USA=1                                                                                                                                                                      |

In [2]:
import pandas as pd

df = pd.read_stata('pwt100.dta')
list(df["country"].unique())

['Aruba',
 'Angola',
 'Anguilla',
 'Albania',
 'United Arab Emirates',
 'Argentina',
 'Armenia',
 'Antigua and Barbuda',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Burundi',
 'Belgium',
 'Benin',
 'Burkina Faso',
 'Bangladesh',
 'Bulgaria',
 'Bahrain',
 'Bahamas',
 'Bosnia and Herzegovina',
 'Belarus',
 'Belize',
 'Bermuda',
 'Bolivia (Plurinational State of)',
 'Brazil',
 'Barbados',
 'Brunei Darussalam',
 'Bhutan',
 'Botswana',
 'Central African Republic',
 'Canada',
 'Switzerland',
 'Chile',
 'China',
 "Côte d'Ivoire",
 'Cameroon',
 'D.R. of the Congo',
 'Congo',
 'Colombia',
 'Comoros',
 'Cabo Verde',
 'Costa Rica',
 'Curaçao',
 'Cayman Islands',
 'Cyprus',
 'Czech Republic',
 'Germany',
 'Djibouti',
 'Dominica',
 'Denmark',
 'Dominican Republic',
 'Algeria',
 'Ecuador',
 'Egypt',
 'Spain',
 'Estonia',
 'Ethiopia',
 'Finland',
 'Fiji',
 'France',
 'Gabon',
 'United Kingdom',
 'Georgia',
 'Ghana',
 'Guinea',
 'Gambia',
 'Guinea-Bissau',
 'Equatorial Guinea',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guyana',
 'China, Hong Kong SAR',
 'Honduras',
 'Croatia',
 'Haiti',
 'Hungary',
 'Indonesia',
 'India',
 'Ireland',
 'Iran (Islamic Republic of)',
 'Iraq',
 'Iceland',
 'Israel',
 'Italy',
 'Jamaica',
 'Jordan',
 'Japan',
 'Kazakhstan',
 'Kenya',
 'Kyrgyzstan',
 'Cambodia',
 'Saint Kitts and Nevis',
 'Republic of Korea',
 'Kuwait',
 "Lao People's DR",
 'Lebanon',
 'Liberia',
 'Saint Lucia',
 'Sri Lanka',
 'Lesotho',
 'Lithuania',
 'Luxembourg',
 'Latvia',
 'China, Macao SAR',
 'Morocco',
 'Republic of Moldova',
 'Madagascar',
 'Maldives',
 'Mexico',
 'North Macedonia',
 'Mali',
 'Malta',
 'Myanmar',
 'Montenegro',
 'Mongolia',
 'Mozambique',
 'Mauritania',
 'Montserrat',
 'Mauritius',
 'Malawi',
 'Malaysia',
 'Namibia',
 'Niger',
 'Nigeria',
 'Nicaragua',
 'Netherlands',
 'Norway',
 'Nepal',
 'New Zealand',
 'Oman',
 'Pakistan',
 'Panama',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Paraguay',
 'State of Palestine',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Saudi Arabia',
 'Sudan',
 'Senegal',
 'Singapore',
 'Sierra Leone',
 'El Salvador',
 'Serbia',
 'Sao Tome and Principe',
 'Suriname',
 'Slovakia',
 'Slovenia',
 'Sweden',
 'Eswatini',
 'Sint Maarten (Dutch part)',
 'Seychelles',
 'Syrian Arab Republic',
 'Turks and Caicos Islands',
 'Chad',
 'Togo',
 'Thailand',
 'Tajikistan',
 'Turkmenistan',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Taiwan',
 'U.R. of Tanzania: Mainland',
 'Uganda',
 'Ukraine',
 'Uruguay',
 'United States',
 'Uzbekistan',
 'St. Vincent and the Grenadines',
 'Venezuela (Bolivarian Republic of)',
 'British Virgin Islands',
 'Viet Nam',
 'Yemen',
 'South Africa',
 'Zambia',
 'Zimbabwe']

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12810 entries, 0 to 12809
Data columns (total 52 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   countrycode    12810 non-null  object
 1   country        12810 non-null  object
 2   currency_unit  12810 non-null  object
 3   year           12810 non-null  int16
 4   rgdpe          10399 non-null  float32
 5   rgdpo          10399 non-null  float32
 6   pop            10399 non-null  float64
 7   emp            9529 non-null   float32
 8   avh            3492 non-null   float64
 9   hc             8637 non-null   float32
 10  ccon           10399 non-null  float32
 11  cda            10399 non-null  float32
 12  cgdpe          10399 non-null  float32
 13  cgdpo          10395 non-null  float32
 14  cn             10314 non-null  float32
 15  ck             7095 non-null   float32
 16  ctfp           6412 non-null   float32
 17  cwtfp          6412 non-null   float32
 18  rgdpna         10399 non-null  float32
 19  rconna         10399 non-null  float32
 20  rdana          10399 non-null  float32
 21  rnna           10314 non-null  float32
 22  rkna           7095 non-null   float32
 23  rtfpna         6412 non-null   float32
 24  rwtfpna        6412 non-null   float32
 25  labsh          7970 non-null   float32
 26  irr            7540 non-null   float32
 27  delta          10314 non-null  float32
 28  xr             10399 non-null  float64
 29  pl_con         10399 non-null  float32
 30  pl_da          10399 non-null  float32
 31  pl_gdpo        10399 non-null  float32
 32  i_cig          10399 non-null  category
 33  i_xm           10399 non-null  category
 34  i_xr           10399 non-null  category
 35  i_outlier      10399 non-null  category
 36  i_irr          7540 non-null   category
 37  cor_exp        1653 non-null   float64
 38  statcap        2117 non-null   float64
 39  csh_c          10399 non-null  float32
 40  csh_i          10399 non-null  float32
 41  csh_g          10399 non-null  float32
 42  csh_x          10399 non-null  float32
 43  csh_m          10399 non-null  float32
 44  csh_r          10399 non-null  float32
 45  pl_c           10399 non-null  float32
 46  pl_i           10399 non-null  float32
 47  pl_g           10399 non-null  float32
 48  pl_x           10399 non-null  float32
 49  pl_m           10399 non-null  float32
 50  pl_n           10314 non-null  float32
 51  pl_k           7095 non-null   float32
dtypes: category(5), float32(38), float64(5), int16(1), object(3)
memory usage: 2.8+ MB

In [4]:
df.head()

,countrycode,country,currency_unit,year,rgdpe,rgdpo,pop,emp,avh,hc,...,csh_x,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k
0,ABW,Aruba,Aruban Guilder,1950,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABW,Aruba,Aruban Guilder,1951,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABW,Aruba,Aruban Guilder,1952,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABW,Aruba,Aruban Guilder,1953,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABW,Aruba,Aruban Guilder,1954,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
# 1. Import the data and filter the two datasets for the chosen two years.
#df_1990 = df[(df["year"]==1990)]
#df_1970 = df[(df["year"]==1970)]

#df

In [110]:
#import pandas_profiling
#df_1990.profile_report()
#df_1990.profile_report().to_file("pwt_profile_report.html")

In [111]:
features = [
   "year",
    "country",
    "hc",
    "ctfp",
    "cwtfp",
    "delta",
    "pl_con",
    "pl_da",
    "pl_gdpo",
    "csh_g",
    "pl_c",
    "pl_i",
    "pl_g",
    #"pl_k",
]

In [112]:
features_logarithmic = [
    #"rgdpe",
    "pop",
    "ccon",
    #"rgdpna",
    "rconna",
    "xr",
]

In [113]:
targeted_features = [
    "rgdpna", # log required
    #"rtfpna", # log not required
]

In [114]:
df.describe()

,year,rgdpe,rgdpo,pop,emp,avh,hc,ccon,cda,cgdpe,...,csh_x,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k
count,12810.000000,1.039900e+04,1.039900e+04,10399.000000,9529.000000,3492.000000,8637.000000,1.039900e+04,1.039900e+04,1.039900e+04,...,10399.000000,10399.000000,10399.000000,10399.000000,10399.000000,10399.000000,10399.000000,10399.000000,10314.000000,7095.000000
mean,1984.500000,3.048523e+05,3.070802e+05,30.962982,14.171166,1986.923200,2.087200,2.249465e+05,3.049463e+05,3.061396e+05,...,0.229317,-0.300829,0.017791,0.370850,0.423964,0.345635,0.409820,0.403422,0.359019,1.333927
std,20.205986,1.214332e+06,1.218457e+06,116.189454,58.056976,284.003338,0.727413,8.882342e+05,1.236096e+06,1.226056e+06,...,0.266793,0.640212,0.216200,0.424091,0.635708,0.408015,0.196283,0.202566,0.435651,1.941819
min,1950.000000,2.036377e+01,2.765232e+01,0.004425,0.001200,1380.607643,1.007038,1.604856e+01,2.176663e+01,2.026185e+01,...,-1.937363,-23.237627,-12.568965,0.015589,0.006002,0.009270,0.007354,0.020806,0.012977,0.064378
25%,1967.000000,6.801782e+03,7.191773e+03,1.579663,0.775101,1788.478805,1.450483,5.892980e+03,7.194495e+03,6.689781e+03,...,0.067027,-0.379584,-0.025204,0.171226,0.191958,0.116110,0.237652,0.240777,0.164152,0.650608
50%,1984.500000,3.031913e+04,3.084435e+04,6.150688,2.856044,1972.355973,1.987572,2.465417e+04,3.134864e+04,3.031841e+04,...,0.140116,-0.200254,0.000326,0.306258,0.377943,0.244554,0.443856,0.452949,0.295862,0.954343
75%,2002.000000,1.559740e+05,1.587386e+05,19.934229,8.266107,2168.035042,2.674011,1.133967e+05,1.532297e+05,1.559242e+05,...,0.300332,-0.102694,0.044529,0.484549,0.557087,0.452951,0.557034,0.541063,0.447566,1.415062
max,2019.000000,2.086051e+07,2.059584e+07,1433.783686,799.306641,3039.794005,4.351568,1.682624e+07,2.138355e+07,2.079136e+07,...,3.523480,32.874020,7.598285,23.122841,34.444988,18.420809,2.056070,4.990355,20.649197,31.931993

In [115]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html
# https://coderzcolumn.com/tutorials/data-science/time-series-resampling-and-moving-window-functions
# https://towardsdatascience.com/time-series-modeling-using-scikit-pandas-and-numpy-682e3b8db8d1

#df_series = pd.Series(data=df["country"][df["country"] == "Switzerland"], index=list(df["year"].unique()))
#df_series = pd.Series(data=df["country"], index=list(df["year"].unique()))
#df_series

In [116]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
log_transformer = FunctionTransformer(np.log1p)
df_log_features = df[features_logarithmic+targeted_features]
df_log = log_transformer.transform(df_log_features)

df_log.head()

   pop  ccon  rconna  xr  rgdpna
0  NaN   NaN     NaN NaN     NaN
1  NaN   NaN     NaN NaN     NaN
2  NaN   NaN     NaN NaN     NaN
3  NaN   NaN     NaN NaN     NaN
4  NaN   NaN     NaN NaN     NaN

In [117]:
df_concat = pd.concat([df[features], df_log], axis=1, join="inner")
len(df_log)

12810

In [118]:
df_cleaned = df_concat.dropna()
len(df_cleaned)
df_cleaned.head()

,year,country,hc,ctfp,cwtfp,delta,pl_con,pl_da,pl_gdpo,csh_g,pl_c,pl_i,pl_g,pop,ccon,rconna,xr,rgdpna
94,1974,Angola,1.025762,0.552020,0.565481,0.037802,0.194362,0.157843,0.162857,0.221853,0.185541,0.100256,0.210469,2.049160,9.983616,10.945770,2.540760e-08,11.069818
95,1975,Angola,1.028297,0.511384,0.536695,0.037406,0.151047,0.121739,0.127804,0.221240,0.144321,0.076586,0.163493,2.082437,9.926695,10.889573,2.555218e-08,11.018525
96,1976,Angola,1.030838,0.473798,0.479260,0.037198,0.154665,0.124070,0.126844,0.215925,0.148727,0.076506,0.165689,2.113784,9.871202,10.835129,2.938362e-08,10.965125
97,1977,Angola,1.033385,0.481119,0.469169,0.036921,0.164700,0.133062,0.132220,0.212701,0.157970,0.084094,0.176923,2.144027,9.887688,10.848621,2.991800e-08,10.973093
98,1978,Angola,1.035939,0.421195,0.431405,0.036449,0.196521,0.159605,0.164013,0.224828,0.188381,0.101402,0.211305,2.173695,9.836812,10.801093,2.991800e-08,10.918638

In [138]:
from sklearn.preprocessing import Normalizer
df_normalized = pd.DataFrame(Normalizer().fit_transform(df_cleaned[features[2:]+features_logarithmic+trageted_feature]),columns=features[2:]+features_logarithmic+trageted_feature)
len(df_normalized)

6412

In [139]:
df_cleaned[features[:2]].reset_index(drop=True)

      year   country
0     1974    Angola
1     1975    Angola
2     1976    Angola
3     1977    Angola
4     1978    Angola
...    ...       ...
6407  2015  Zimbabwe
6408  2016  Zimbabwe
6409  2017  Zimbabwe
6410  2018  Zimbabwe
6411  2019  Zimbabwe

[6412 rows x 2 columns]

In [140]:
df_normalized.head()

,hc,ctfp,cwtfp,delta,pl_con,pl_da,pl_gdpo,csh_g,pl_c,pl_i,pl_g,pop,ccon,rconna,xr,rgdpna
0,0.054977,0.029586,0.030307,0.002026,0.010417,0.008460,0.008728,0.011890,0.009944,0.005373,0.011280,0.109826,0.535080,0.586647,1.361741e-09,0.593296
1,0.055391,0.027547,0.028910,0.002015,0.008136,0.006558,0.006884,0.011918,0.007774,0.004125,0.008807,0.112175,0.534721,0.586589,1.376419e-09,0.593535
2,0.055805,0.025649,0.025945,0.002014,0.008373,0.006717,0.006867,0.011689,0.008051,0.004142,0.008970,0.114431,0.534384,0.586567,1.590703e-09,0.593605
3,0.055866,0.026010,0.025364,0.001996,0.008904,0.007194,0.007148,0.011499,0.008540,0.004546,0.009565,0.115909,0.534543,0.586492,1.617411e-09,0.593221
4,0.056261,0.022875,0.023429,0.001980,0.010673,0.008668,0.008907,0.012210,0.010231,0.005507,0.011476,0.118052,0.534232,0.586602,1.624831e-09,0.592986

In [141]:
df_normalized = pd.concat([df_cleaned[features[:2]].reset_index(drop=True),df_normalized], axis=1)
df_normalized.head()

,year,country,hc,ctfp,cwtfp,delta,pl_con,pl_da,pl_gdpo,csh_g,pl_c,pl_i,pl_g,pop,ccon,rconna,xr,rgdpna
0,1974,Angola,0.054977,0.029586,0.030307,0.002026,0.010417,0.008460,0.008728,0.011890,0.009944,0.005373,0.011280,0.109826,0.535080,0.586647,1.361741e-09,0.593296
1,1975,Angola,0.055391,0.027547,0.028910,0.002015,0.008136,0.006558,0.006884,0.011918,0.007774,0.004125,0.008807,0.112175,0.534721,0.586589,1.376419e-09,0.593535
2,1976,Angola,0.055805,0.025649,0.025945,0.002014,0.008373,0.006717,0.006867,0.011689,0.008051,0.004142,0.008970,0.114431,0.534384,0.586567,1.590703e-09,0.593605
3,1977,Angola,0.055866,0.026010,0.025364,0.001996,0.008904,0.007194,0.007148,0.011499,0.008540,0.004546,0.009565,0.115909,0.534543,0.586492,1.617411e-09,0.593221
4,1978,Angola,0.056261,0.022875,0.023429,0.001980,0.010673,0.008668,0.008907,0.012210,0.010231,0.005507,0.011476,0.118052,0.534232,0.586602,1.624831e-09,0.592986

In [142]:
df_normalized["country"].unique()[0]

'Angola'

In [143]:
df_normalized["year"].unique()[0]

1974

In [144]:
df_normalized[df_normalized["country"]==df_normalized["country"].unique()[0]].sort_values("year")[2:]

,year,country,hc,ctfp,cwtfp,delta,pl_con,pl_da,pl_gdpo,csh_g,pl_c,pl_i,pl_g,pop,ccon,rconna,xr,rgdpna
2,1976,Angola,0.055805,0.025649,0.025945,0.002014,0.008373,0.006717,0.006867,0.011689,0.008051,0.004142,0.008970,0.114431,0.534384,0.586567,1.590703e-09,0.593605
3,1977,Angola,0.055866,0.026010,0.025364,0.001996,0.008904,0.007194,0.007148,0.011499,0.008540,0.004546,0.009565,0.115909,0.534543,0.586492,1.617411e-09,0.593221
4,1978,Angola,0.056261,0.022875,0.023429,0.001980,0.010673,0.008668,0.008907,0.012210,0.010231,0.005507,0.011476,0.118052,0.534232,0.586602,1.624831e-09,0.592986
5,1979,Angola,0.056386,0.023172,0.022965,0.001950,0.011786,0.009548,0.009564,0.012115,0.011213,0.006008,0.012779,0.119649,0.533873,0.586495,1.624419e-09,0.592998
6,1980,Angola,0.056469,0.023231,0.022559,0.001917,0.015103,0.012359,0.012444,0.010086,0.014443,0.007830,0.016574,0.121201,0.533619,0.585373,1.622810e-09,0.593697
7,1981,Angola,0.056944,0.022145,0.022221,0.001884,0.013966,0.011701,0.011764,0.010900,0.012827,0.007888,0.016384,0.122845,0.535059,0.586596,1.621946e-09,0.590941
8,1982,Angola,0.057272,0.021865,0.023283,0.001855,0.013752,0.011377,0.011572,0.012154,0.012447,0.007713,0.016208,0.124179,0.535807,0.587461,1.616798e-09,0.589066
9,1983,Angola,0.057521,0.020480,0.021033,0.001823,0.013745,0.011729,0.012059,0.012140,0.012458,0.007882,0.016362,0.125342,0.536199,0.587419,1.609423e-09,0.588592
10,1984,Angola,0.057635,0.020633,0.020448,0.001788,0.012882,0.011163,0.011662,0.013431,0.010815,0.007797,0.016373,0.126200,0.536251,0.588180,1.598331e-09,0.587648
11,1985,Angola,0.057773,0.020668,0.019293,0.001755,0.014867,0.013408,0.013538,0.011575,0.012979,0.009412,0.019100,0.127089,0.538119,0.588049,1.587951e-09,0.585658
12,1986,Angola,0.058341,0.017441,0.017183,0.001732,0.015841,0.014563,0.014443,0.014234,0.013967,0.010550,0.019372,0.128906,0.536496,0.586904,1.589319e-09,0.587823
13,1987,Angola,0.058725,0.018838,0.017019,0.001705,0.016144,0.014733,0.014716,0.013191,0.014253,0.010851,0.019441,0.130306,0.535085,0.585573,1.585613e-09,0.590038
14,1988,Angola,0.059051,0.016827,0.015449,0.001682,0.017807,0.016661,0.016790,0.014778,0.016590,0.012343,0.019815,0.131551,0.534437,0.584778,1.580268e-09,0.590914
15,1989,Angola,0.059425,0.017138,0.015142,0.001663,0.019416,0.018277,0.018368,0.013209,0.018488,0.013327,0.021186,0.132872,0.535261,0.584791,1.576172e-09,0.589586
16,1990,Angola,0.059999,0.017580,0.014441,0.001653,0.020804,0.019409,0.018972,0.011753,0.019034,0.013676,0.024345,0.134606,0.534739,0.584415,1.577283e-09,0.589767
17,1991,Angola,0.061376,0.014428,0.014905,0.001677,0.037123,0.025146,0.026100,0.015941,0.030994,0.007697,0.043576,0.137540,0.527948,0.580592,2.932851e-09,0.595988
18,1992,Angola,0.062534,0.016607,0.015740,0.001715,0.054477,0.025341,0.023271,0.012158,0.067115,0.001702,0.043347,0.139941,0.525271,0.577939,1.345825e-08,0.596130
19,1993,Angola,0.065749,0.013257,0.010875,0.001806,0.048205,0.022065,0.021271,0.007937,0.037758,0.004744,0.061989,0.146900,0.520158,0.574903,1.477756e-07,0.603411
20,1994,Angola,0.065949,0.012795,0.010483,0.001809,0.037096,0.020925,0.020702,0.009416,0.027579,0.007552,0.048487,0.147084,0.524455,0.579172,3.273039e-06,0.598120
21,1995,Angola,0.065879,0.009960,0.011350,0.001851,0.015955,0.009951,0.011246,0.013302,0.021198,0.004977,0.010027,0.146646,0.527370,0.581203,1.489271e-04,0.597307
22,1996,Angola,0.067953,0.011116,0.011353,0.002044,0.021273,0.010158,0.012124,0.004587,0.010739,0.005699,0.048284,0.150958,0.517454,0.568285,6.650845e-03,0.615129
23,1997,Angola,0.066037,0.010145,0.011033,0.002065,0.018343,0.012167,0.013309,0.013473,0.024574,0.006099,0.011210,0.146391,0.529967,0.582114,1.092075e-02,0.593741
24,1998,Angola,0.066965,0.009730,0.011831,0.002093,0.016478,0.009926,0.010573,0.006843,0.007640,0.005181,0.043248,0.148126,0.531063,0.576601,1.756071e-02,0.596696
25,1999,Angola,0.066844,0.008791,0.010290,0.002095,0.012806,0.008855,0.010021,0.015180,0.018370,0.004704,0.006564,0.147532,0.531722,0.581464,6.958238e-02,0.589010
26,2000,Angola,0.068314,0.007504,0.006572,0.002118,0.023636,0.015943,0.017003,0.013012,0.023762,0.005232,0.023492,0.150447,0.521756,0.571876,1.264993e-01,0.595740
27,2001,Angola,0.067405,0.007619,0.007401,0.002051,0.019612,0.015167,0.015421,0.010335,0.016684,0.006172,0.026572,0.148737,0.525701,0.572224,1.616495e-01,0.584212
28,2002,Angola,0.067209,0.008732,0.007517,0.002015,0.017032,0.016763,0.016632,0.010250,0.017665,0.016252,0.015804,0.148598,0.520784,0.567042,1.932644e-01,0.584280
29,2003,Angola,0.067080,0.008862,0.007678,0.001996,0.019437,0.018430,0.017656,0.010103,0.019541,0.016598,0.019236,0.148616,0.519058,0.564282,2.178535e-01,0.579498
30,2004,Angola,0.067222,0.010345,0.007888,0.002009,0.021152,0.020356,0.018939,0.008613,0.023986,0.019057,0.015744,0.149256,0.517603,0.562166,2.219776e-01,0.580803
31,2005,Angola,0.067192,0.013382,0.008343,0.002021,0.025917,0.025002,0.022246,0.007290,0.026846,0.023553,0.024245,0.149539,0.517031,0.559833,2.219976e-01,0.582361
32,2006,Angola,0.067213,0.016236,0.008886,0.002020,0.029457,0.027794,0.024050,0.006505,0.030369,0.025096,0.027872,0.149958,0.519209,0.558642,2.161667e-01,0.582813
33,2007,Angola,0.067169,0.016529,0.009569,0.002005,0.033207,0.031322,0.026580,0.006732,0.035185,0.028407,0.029859,0.150247,0.520987,0.556572,2.118796e-01,0.583679
34,2008,Angola,0.067047,0.017613,0.010765,0.002020,0.036855,0.034956,0.029406,0.006638,0.037456,0.032478,0.035869,0.150358,0.523656,0.555082,2.085812e-01,0.582577
35,2009,Angola,0.067357,0.011760,0.010415,0.002074,0.035785,0.033710,0.029276,0.008146,0.036535,0.031094,0.034293,0.151418,0.526389,0.554211,2.103296e-01,0.580511
36,2010,Angola,0.067502,0.014539,0.010453,0.002108,0.031612,0.028314,0.026048,0.006976,0.032272,0.023684,0.030309,0.152082,0.529122,0.552505,2.158532e-01,0.578892
37,2011,Angola,0.067053,0.017446,0.012308,0.002135,0.032154,0.028285,0.026444,0.007508,0.033285,0.022850,0.030240,0.151963,0.534654,0.552964,2.143700e-01,0.573793
38,2012,Angola,0.066814,0.019086,0.013678,0.002158,0.031590,0.028895,0.026966,0.007449,0.032368,0.024689,0.030150,0.152284,0.537789,0.551242,2.132941e-01,0.572738
39,2013,Angola,0.066488,0.019991,0.015602,0.002153,0.030336,0.029295,0.027693,0.010097,0.032322,0.027184,0.027412,0.152368,0.541822,0.551350,2.117001e-01,0.569349
40,2014,Angola,0.066397,0.020326,0.016857,0.002138,0.028934,0.028766,0.027469,0.009426,0.031515,0.028392,0.024060,0.152954,0.545679,0.549282,2.111956e-01,0.567916
41,2015,Angola,0.066510,0.018735,0.017943,0.002119,0.023958,0.024677,0.023712,0.009563,0.026287,0.026270,0.018654,0.153973,0.546709,0.547368,2.195751e-01,0.566489
42,2016,Angola,0.066659,0.018744,0.017248,0.002086,0.021172,0.021933,0.021510,0.008767,0.023255,0.024165,0.015549,0.155044,0.544882,0.546821,2.330207e-01,0.563756
43,2017,Angola,0.066792,0.018526,0.016298,0.002039,0.023934,0.024892,0.024154,0.009032,0.027123,0.028170,0.015748,0.156045,0.546269,0.546269,2.329475e-01,0.562011
44,2018,Angola,0.066982,0.018484,0.015454,0.002002,0.019434,0.019222,0.019733,0.008800,0.022936,0.018469,0.010669,0.157152,0.543820,0.543662,2.514949e-01,0.559892
45,2019,Angola,0.067105,0.017241,0.014759,0.001965,0.017275,0.016898,0.017237,0.009044,0.019841,0.015525,0.010868,0.158084,0.541434,0.541238,2.672542e-01,0.557457

In [33]:
#window_frame = 2
#tmp_df_normalized = df_normalized[window_frame:].copy()

In [38]:
#df_normalized[0][window_frame:]

2       0.055805
3       0.055866
4       0.056261
5       0.056386
6       0.056469
          ...
6407    0.136172
6408    0.138144
6409    0.139178
6410    0.140563
6411    0.143067
Name: 0, Length: 6410, dtype: float64

In [167]:
window_frame = 2
#features_framed = df_normalized.columns.values
features_framed = ["hc","ccon"]
#tmp_df_normalized = df_normalized[window_frame:].copy()
tmp_df_windowed = pd.DataFrame(columns=features+features_logarithmic+trageted_feature)

for ff in features_framed:
    for i in range(window_frame):
        tmp_df_windowed[ff+"-"+str(i+1)] = []

#df_normalized[df_normalized["country"]==df_normalized["country"].unique()[0]].sort_values("year")[2:]

for c in df_normalized["country"].unique():
    for w in range(window_frame):
        #print(df_normalized[df_normalized["country"]==c].sort_values("year")[2:])
        tmp_df_country = df_normalized[df_normalized["country"]==c].sort_values("year")
        tmp_df_country = pd.concat([tmp_df_country[:2].empty,tmp_df_country]).reset_index(drop=True)
        #pd.concat([tmp_df_country[:2]], ignore_index=True)
        print(tmp_df_country[features_framed][:-window_frame])
        #print(tmp_df_country[:2])
        #tmp_df_windowed = pd.concat([tmp_df_windowed, df_normalized[df_normalized["country"]==c].sort_values("year")[2:]])
        break
    break
    #    for f in features_framed:

    #        tmp_df_normalized = pd.concat(tmp_df_normalized,df_normalized[f][window_frame:])
#tmp_df_windowed

TypeError: cannot concatenate object of type '<class 'bool'>'; only Series and DataFrame objs are valid

In [125]:
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = pd.DataFrame(df_normalized,columns=df_normalized.columns[:-1])
y = pd.DataFrame(df_normalized,columns=[df_normalized.columns[-1]])

X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=1, test_size=0.2)

sc_X = StandardScaler()
X_trainscaled=sc_X.fit_transform(X_train)
X_testscaled=sc_X.transform(X_test)

sc_y = StandardScaler()
y_trainscaled=sc_y.fit_transform(y_train)
y_testscaled=sc_y.transform(y_test)

In [126]:
y_testscaled

array([[ 0.56347856],
       [ 0.48446071],
       [ 0.24114127],
       ...,
       [-0.64740587],
       [-0.08971093],
       [-0.57025485]])

In [127]:
X_trainscaled

array([[-0.18171014, -0.85588352, -0.88663896, ...,  0.1689676 ,
        -0.02322338, -0.18447572],
       [-0.46363377, -0.80149077, -0.79898378, ...,  0.82751132,
        -0.96285517,  0.70177037],
       [ 0.6213142 ,  0.48109582,  0.28611787, ..., -0.02904315,
        -0.77138969,  0.38206198],
       ...,
       [-1.3226293 , -0.78989554, -0.53362006, ...,  0.16318248,
         0.038612  , -0.738351  ],
       [ 0.6608038 ,  0.01793949,  0.05968583, ...,  0.67205318,
        -0.64012252,  0.66939694],
       [-0.51395   , -0.62588328, -0.99818965, ..., -0.15569536,
        -0.44016011,  1.25428371]])

In [128]:
reg = MLPRegressor(hidden_layer_sizes=(18,3,18),activation="relu", alpha=0.01, random_state=1, max_iter=2000).fit(X_trainscaled, y_trainscaled)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

In [129]:
from sklearn.metrics import r2_score

y_pred = reg.predict(X_testscaled)
print("The Score with ", (r2_score(y_pred, y_testscaled)))

The Score with  0.9960763165411954

In [111]:
#from joblib import dump, load
#dump(reg, 'model.joblib')
#dump(sc_X, 'sc_X.joblib')
#dump(sc_y, 'sc_y.joblib')

['model.joblib']

In [138]:
%run main_romain_claret_and_sylvain_robert-nicoud_lab7.py

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

The Score with (1.0 is awesome) 0.9854604824145102